### PR TITLE
Mobistar --> Orange BE

### PR DESCRIPTION
**Pull request by spottech**
Change Mobistar to Orange BE, it's the new name of compagny
Also fix apn config for dropped upload and download after somes Mb

### CODE REVIEW

**Comment by regalstreak** [comment]
remove the extra commit and resubmit the pr

**Comment by xdevs23** [comment]
@regalstreak we can pick the first one only too lol

**Comment by regalstreak** [comment]
How?

Yes ik we can do manually but how do we do it via the gui?

**Comment by xdevs23** [comment]
@regalstreak already done

**Comment by regalstreak** [comment]
how?
edit: nvm manually :3

**Comment by xdevs23** [comment]
@regalstreak yes, manually

**Comment by spottech** [comment]
hi, sorry, I do not know why github push all my commits

**Comment by xdevs23** [comment]
Well nvm, I already picked the wanted commit.

**Pull request closed without merging**
